 services:
  app:
    image: node:bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    expose:
      - "8088"
    ports:
      - "8088:8088"
    networks:
      - front-tier
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  front-tier: {}